### ISSUE TITLE
hg.clone won't return hgRepo

### ISSUE THREAD

**Issue by 52linyuepeng** [jdalrymple/node-hg-plus#3]
On line 71-72 of hg.js

```javascript
return Command.run('hg clone', newRepo.path, [from, newRepo.path])
   .then(() => newRepo)
```

It goes wrong that `newRepo` will not return from promise but as the parameter of the next then.

Thus,

```javascript
const repo = await hg.clone(url)
console.log(repo);  // undefined
```

**Comment by TrainL** [comment]
sorry, I missed `asCallback`.
It's my own fault.
If the destination dir is not empty, the promise above will be caught which makes the return of hg.clone undefined.

**Comment by jdalrymple** [comment]
I should trickle up that error, otherwise it's confusing. I'll fix it today and update the docs!
